### ISSUE TITLE
Web Interface crashing on fresh install of Deb 12.

### ISSUE THREAD

**Issue by jcid2023** [nostar/urfd#11]
PHP Fatal error:  Uncaught TypeError: mktime(): Argument #1 ($hour) must be of type int, string given in /var/www/html/pgs/functions.php:44\nStack trace:\

Web interface shows fine until someone connects and then white screens. Fresh Deb12 install, Fresh git pull. Installed per the directions.

**Comment by jcid2023** [comment]
[Sat Dec 21 20:10:41.558175 2024] [php:warn] [pid 1186:tid 1186] [client 172.16.1.3:62276] PHP Warning:  Undefined array key 4 in /var/www/html/pgs/functions.php on line 27
[Sat Dec 21 20:10:41.558196 2024] [php:warn] [pid 1186:tid 1186] [client 172.16.1.3:62276] PHP Warning:  Undefined array key 2 in /var/www/html/pgs/functions.php on line 29
[Sat Dec 21 20:10:41.558303 2024] [php:error] [pid 1186:tid 1186] [client 172.16.1.3:62276] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #1 ($hour) must be of type int, string given in /var/www/html/pgs/functions.php:44\nStack trace:\n#0 /var/www/html/pgs/functions.php(44): mktime()\n#1 /var/www/html/pgs/class.node.php(20): ParseTime()\n#2 /var/www/html/pgs/class.reflector.php(63): Node->__construct()\n#3 /var/www/html/index.php(32): xReflector->LoadXML()\n#4 {main}\n  thrown in /var/www/html/pgs/functions.php on line 44
[Sat Dec 21 20:10:42.315613 2024] [php:warn] [pid 1187:tid 1187] [client 172.16.1.3:62277] PHP Warning:  Undefined array key 3 in /var/www/html/pgs/functions.php on line 22
[Sat Dec 21 20:10:42.315660 2024] [php:warn] [pid 1187:tid 1187] [client 172.16.1.3:62277] PHP Warning:  Undefined array key 4 in /var/www/html/pgs/functions.php on line 27
[Sat Dec 21 20:10:42.315678 2024] [php:warn] [pid 1187:tid 1187] [client 172.16.1.3:62277] PHP Warning:  Undefined array key 2 in /var/www/html/pgs/functions.php on line 29
[Sat Dec 21 20:10:42.315755 2024] [php:error] [pid 1187:tid 1187] [client 172.16.1.3:62277] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #1 ($hour) must be of type int, string given in /var/www/html/pgs/functions.php:44\nStack trace:\n#0 /var/www/html/pgs/functions.php(44): mktime()\n#1 /var/www/html/pgs/class.node.php(20): ParseTime()\n#2 /var/www/html/pgs/class.reflector.php(63): Node->__construct()\n#3 /var/www/html/index.php(32): xReflector->LoadXML()\n#4 {main}\n  thrown in /var/www/html/pgs/functions.php on line 44

**Comment by jcid2023** [comment]
reverted to php7.4 on deb12 for now to fix the issue. Dates and times still showing incorrectly though. Same result on deb11 php version 5.6 on up.

examples:
live: http://monitor.wny-digital.network
dev: http://ref.wny-digital.network
